services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bot
    networks:
      base:
        ipv4_address: 172.20.50.2
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./.env
        target: /usr/src/app/.env

networks:
  base:
    ipam:
      config:
        - subnet: 172.20.50.0/24
          gateway: 172.20.50.1
